### ISSUE TITLE
Homework link

### ISSUE THREAD

**Issue by Alexikon** [rstropek-teaching/form-validation-quiz-4bhif-Alexikon#1]
Here is a link for testing it: http://form-val-alext.bplaced.net/

**Comment by Alexikon** [comment]
link funktioniert gerade nicht, weil es die cookies von der battleship seite gelesen hat, weil ich battleship account gelöscht habe, aber einen neuen account für form validation gemacht habe und es jetzt denkt, dass die form validation auch gelöscht werden soll.

**Comment by Alexikon** [comment]
jedenfalls äre das meine einzige erklärung, warum beim 2. Anmelden die seite sofort angezeigt hat, dass die seite gelöscht wird.

**Comment by rstropek** [comment]
Hi @Alexikon 

I recommend using the free pricing tier of the *Azure App Service* cloud service to host static websites. You can find a description how to publish a static website [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-html#push-to-azure-from-git). With your [Microsoft Imagine/Dream Spark Account](https://imagine.microsoft.com/en-us/custom/Dreamspark), you should be able to get a free Azure subscription without a credit card.

This service is free forever for small web apps. However, it can scale to professional web applications with a huge number of users. So you can learn to use the same cloud computing tools that some of the largest websites in the world use.

Greetings,
Rainer Stropek.
